// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "a2a1ed73a062ff0192262c653c5950827c2b890e19163fa07181f78969dd5cf8")
