// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "4c3a25a2097c3e31d06c7628fbfaffba680bfbf4d83f8261a876a72d7bfc4f6c")
