// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "8cda8096836e4c849dfa3d9f274ebfda643de6b1cc268d1a4a1d5a2e6007932c")
